#!/usr/bin/env bash
# Copyright information
#
# © [2026] LimX Dynamics Technology Co., Ltd. All rights reserved.

set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PCT_ROOT="${ROOT_DIR}/PCT_planner-RC2026_Map_Planner"
BUILDER="${PCT_ROOT}/tomography/scripts/build_tomogram_offline.py"
PYTHON_EXECUTABLE="${PYTHON_EXECUTABLE:-/usr/bin/python3}"
MAP_TOOLS_SITE="${PCT_MAP_TOOLS_SITE:-${ROOT_DIR}/.map-tools/site}"
DEFAULT_SOURCE_PCD="${ROOT_DIR}/FAST_LIO/PCD/rs_fairy_map.pcd"
PCD_SELECTOR="${PCD_SELECTOR:-${ROOT_DIR}/select_pcd_map.py}"
NAVIGATION_MAP_SELECTOR="${NAVIGATION_MAP_SELECTOR:-${ROOT_DIR}/select_navigation_map.py}"
PCD_SELECTION_MODE="${PCD_SELECTION_MODE:-prompt}"

usage() {
  cat <<'EOF'
Usage:
  ./prepare_fast_lio_pcd_map.sh [OPTIONS]
  ./prepare_fast_lio_pcd_map.sh /path/to/map.pcd [OPTIONS]

With no PCD path, an interactive terminal lists saved and archived PCD maps
before processing. A non-interactive command keeps the latest map saved by
run_fast_lio_mapping_humble.sh at FAST_LIO/PCD/rs_fairy_map.pcd. An explicit
PCD path keeps the original basename-based naming behavior.

Options:
  --name NAME              Named output prefix (default: PCD basename)
  --list-pcds              List selectable PCD maps and exit
  --latest-pcd             Select the newest listed PCD without prompting
  --profile standard|nx-large
  --large-map              Alias for --profile nx-large
  --resolution METERS      Override PCT XY grid resolution, range (0, 1]
  --xy-dilation-cells N    XY hole filling radius, 0..4 (default: 1)
  --ground-h METERS        Override automatic ground height
  --localization-pcd PATH  Full-range PCD used by ICP localization
  --pair-manifest PATH     Dual-map manifest generated by ./navi.sh save
  --no-activate            Build named outputs without replacing map.pcd/map.pickle
  --force                  Replace existing named outputs

Without --localization-pcd, the source PCD is used by both localization and
PCT. In dual-map mode, the source PCD is the near-field PCT input while the
full-range localization PCD must be authenticated by --pair-manifest. Stop
localization/navigation before activating a map.
EOF
}

if [[ $# -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
  usage
  exit 0
fi
AUTO_SOURCE=false
if [[ $# -gt 0 && "$1" != -* ]]; then
  SOURCE_PCD="$1"
  shift
else
  SOURCE_PCD="${DEFAULT_SOURCE_PCD}"
  AUTO_SOURCE=true
fi
NAME=""
PROFILE="standard"
RESOLUTION=""
XY_DILATION_CELLS=1
GROUND_H=""
LOCALIZATION_PCD=""
PAIR_MANIFEST=""
ACTIVATE=true
FORCE=false
LIST_PCDS=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      NAME="$2"
      shift 2
      ;;
    --list-pcds)
      LIST_PCDS=true
      shift
      ;;
    --latest-pcd)
      PCD_SELECTION_MODE=latest
      shift
      ;;
    --profile)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      PROFILE="$2"
      shift 2
      ;;
    --large-map)
      PROFILE="nx-large"
      shift
      ;;
    --resolution)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      RESOLUTION="$2"
      shift 2
      ;;
    --xy-dilation-cells)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      XY_DILATION_CELLS="$2"
      shift 2
      ;;
    --ground-h)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      GROUND_H="$2"
      shift 2
      ;;
    --localization-pcd)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      LOCALIZATION_PCD="$2"
      shift 2
      ;;
    --pair-manifest)
      [[ $# -ge 2 ]] || { usage >&2; exit 2; }
      PAIR_MANIFEST="$2"
      shift 2
      ;;
    --no-activate)
      ACTIVATE=false
      shift
      ;;
    --force)
      FORCE=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ -x "${PYTHON_EXECUTABLE}" ]] || {
  echo "Python executable not found: ${PYTHON_EXECUTABLE}" >&2
  exit 1
}
if [[ "${AUTO_SOURCE}" == true ]]; then
  [[ -f "${PCD_SELECTOR}" ]] || {
    echo "PCD selector not found: ${PCD_SELECTOR}" >&2
    exit 1
  }
  if [[ "${LIST_PCDS}" == true ]]; then
    "${PYTHON_EXECUTABLE}" "${PCD_SELECTOR}" --root "${ROOT_DIR}" --mode list
    exit $?
  fi
  case "${PCD_SELECTION_MODE,,}" in
    prompt)
      if [[ -t 0 && -t 1 ]]; then
        SOURCE_PCD="$("${PYTHON_EXECUTABLE}" "${PCD_SELECTOR}" \
          --root "${ROOT_DIR}" --mode prompt)"
      else
        echo "No interactive terminal; selecting ${DEFAULT_SOURCE_PCD}"
      fi
      ;;
    latest)
      SOURCE_PCD="$("${PYTHON_EXECUTABLE}" "${PCD_SELECTOR}" \
        --root "${ROOT_DIR}" --mode latest)"
      ;;
    *)
      echo "PCD_SELECTION_MODE must be prompt or latest." >&2
      exit 2
      ;;
  esac
elif [[ "${LIST_PCDS}" == true || "${PCD_SELECTION_MODE,,}" != "prompt" ]]; then
  echo "Do not combine an explicit PCD path with --list-pcds, --latest-pcd, or PCD_SELECTION_MODE." >&2
  exit 2
fi

[[ -f "${SOURCE_PCD}" ]] || { echo "PCD not found: ${SOURCE_PCD}" >&2; exit 1; }
SOURCE_PCD="$(realpath -e "${SOURCE_PCD}")"
if [[ -z "${LOCALIZATION_PCD}" ]]; then
  LOCALIZATION_PCD="${SOURCE_PCD}"
fi
[[ -f "${LOCALIZATION_PCD}" ]] || {
  echo "Localization PCD not found: ${LOCALIZATION_PCD}" >&2
  exit 1
}
LOCALIZATION_PCD="$(realpath -e "${LOCALIZATION_PCD}")"
DUAL_MAP=false
if [[ "${LOCALIZATION_PCD}" != "${SOURCE_PCD}" ]]; then
  DUAL_MAP=true
  [[ -n "${PAIR_MANIFEST}" ]] || {
    echo "Dual-map mode requires --pair-manifest from the same mapping session." >&2
    exit 2
  }
fi
if [[ -n "${PAIR_MANIFEST}" ]]; then
  [[ -f "${PAIR_MANIFEST}" ]] || {
    echo "Dual-map manifest not found: ${PAIR_MANIFEST}" >&2
    exit 1
  }
  PAIR_MANIFEST="$(realpath -e "${PAIR_MANIFEST}")"
  "${PYTHON_EXECUTABLE}" - \
    "${PAIR_MANIFEST}" "${LOCALIZATION_PCD}" "${SOURCE_PCD}" <<'PY'
import hashlib
import json
import sys
from pathlib import Path


def sha256_file(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(4 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


manifest_path = Path(sys.argv[1])
localization_path = Path(sys.argv[2])
pct_source_path = Path(sys.argv[3])
with manifest_path.open("r", encoding="utf-8") as stream:
    payload = json.load(stream)
if payload.get("schema_version") != 1:
    raise RuntimeError("unsupported dual-map manifest schema")
if payload.get("same_mapping_session") is not True:
    raise RuntimeError("dual-map manifest does not certify one mapping session")
if payload.get("coordinate_frame") != "camera_init":
    raise RuntimeError("dual-map manifest has an unexpected coordinate frame")
for label, path, key in (
    ("localization", localization_path, "localization_pcd"),
    ("PCT source", pct_source_path, "pct_source_pcd"),
):
    record = payload.get(key)
    if not isinstance(record, dict):
        raise RuntimeError("dual-map manifest is missing %s" % key)
    if record.get("name") != path.name:
        raise RuntimeError("%s PCD name does not match the manifest" % label)
    if record.get("sha256") != sha256_file(path):
        raise RuntimeError("%s PCD hash does not match the manifest" % label)
localization_range = float(payload["localization_pcd"]["max_range_m"])
pct_range = float(payload["pct_source_pcd"]["max_range_m"])
if not (0.2 < pct_range <= localization_range <= 200.0):
    raise RuntimeError("dual-map manifest contains invalid range limits")
registration_range = payload.get("registration_max_range_m")
if registration_range is not None:
  registration_range = float(registration_range)
  if not (0.2 < registration_range <= localization_range):
    raise RuntimeError("dual-map manifest contains an invalid registration range")
PY
fi
if [[ -z "${NAME}" ]]; then
  if [[ "${AUTO_SOURCE}" == true && \
        "${SOURCE_PCD}" == "$(realpath -e "${DEFAULT_SOURCE_PCD}" 2>/dev/null || true)" ]]; then
    NAME="rs_fairy_$(date -r "${SOURCE_PCD}" +%Y%m%d_%H%M%S)"
  else
    NAME="$(basename "${SOURCE_PCD}")"
    NAME="${NAME%.*}"
    NAME="${NAME#fast_lio_}"
  fi
fi
[[ "${NAME}" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || {
  echo "NAME may contain only letters, numbers, dot, underscore and dash." >&2
  exit 2
}
case "${PROFILE}" in
  standard|nx-large) ;;
  *) echo "Unsupported profile: ${PROFILE}" >&2; exit 2 ;;
esac
if [[ -n "${RESOLUTION}" ]]; then
  [[ "${RESOLUTION}" =~ ^([0-9]+([.][0-9]*)?|[.][0-9]+)$ ]] &&
    awk -v value="${RESOLUTION}" 'BEGIN { exit !(value > 0.0 && value <= 1.0) }' || {
      echo "--resolution must be greater than 0 and no more than 1.0 m." >&2
      exit 2
    }
fi
[[ "${XY_DILATION_CELLS}" =~ ^[0-4]$ ]] || {
  echo "--xy-dilation-cells must be an integer in [0, 4]." >&2
  exit 2
}
[[ -f "${BUILDER}" ]] || { echo "PCT builder not found: ${BUILDER}" >&2; exit 1; }

if [[ "${AUTO_SOURCE}" == true ]]; then
  echo "Selected source PCD map: ${SOURCE_PCD}"
  echo "Automatic map name: ${NAME}"
fi

if [[ -d "${MAP_TOOLS_SITE}" ]]; then
  export PYTHONPATH="${MAP_TOOLS_SITE}${PYTHONPATH:+:${PYTHONPATH}}"
fi
if [[ -d /usr/local/cuda ]]; then
  export CUDA_PATH="${CUDA_PATH:-/usr/local/cuda}"
  export PATH="${CUDA_PATH}/bin:${PATH}"
  export LD_LIBRARY_PATH="${CUDA_PATH}/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
fi

PCD_DIR="${PCT_ROOT}/rsc/pcd"
TOMOGRAM_DIR="${PCT_ROOT}/rsc/tomogram"
NAMED_PCD="${PCD_DIR}/fast_lio_${NAME}.pcd"
NAMED_PCT_SOURCE="${PCD_DIR}/fast_lio_${NAME}.pct-source.pcd"
NAMED_PAIR_MANIFEST="${PCD_DIR}/fast_lio_${NAME}.map-pair.json"
NAMED_TOMOGRAM="${TOMOGRAM_DIR}/fast_lio_${NAME}.pickle"
ACTIVE_PCD="${PCD_DIR}/map.pcd"
ACTIVE_PCT_SOURCE="${PCD_DIR}/map.pct-source.pcd"
ACTIVE_TOMOGRAM="${TOMOGRAM_DIR}/map.pickle"
BUILD_DIR="${PCT_ROOT}/rsc/.build/fast_lio_${NAME}.$$"
BUILD_TOMOGRAM="${BUILD_DIR}/map.pickle"
mkdir -p "${PCD_DIR}" "${TOMOGRAM_DIR}" "${BUILD_DIR}"
trap 'rm -rf "${BUILD_DIR}"' EXIT

named_output_exists=false
for output in "${NAMED_PCD}" "${NAMED_TOMOGRAM}"; do
  [[ ! -e "${output}" ]] || named_output_exists=true
done
if [[ "${DUAL_MAP}" == true ]]; then
  for output in "${NAMED_PCT_SOURCE}" "${NAMED_PAIR_MANIFEST}"; do
    [[ ! -e "${output}" ]] || named_output_exists=true
  done
fi
if [[ "${FORCE}" != true && "${named_output_exists}" == true ]]; then
  echo "Named output already exists; use --force: fast_lio_${NAME}" >&2
  exit 1
fi
if [[ "${ACTIVATE}" == true ]] && pgrep -f '[r]un_.*navigation.*humble|[n]avigation_plan.py|[f]astlio_mapping' >/dev/null 2>&1; then
  echo "Localization or navigation appears to be running; refusing map activation." >&2
  exit 1
fi

configure_python_cuda_runtime() {
  local user_site nvidia_root directory joined
  local -a cuda_library_dirs=()
  user_site="$("${PYTHON_EXECUTABLE}" -c 'import site; print(site.getusersitepackages())')"
  nvidia_root="${user_site}/nvidia"
  if [[ -d "${nvidia_root}" ]]; then
    while IFS= read -r -d '' directory; do
      cuda_library_dirs+=("${directory}")
    done < <(find "${nvidia_root}" -mindepth 2 -maxdepth 2 -type d -name lib -print0 | sort -z)
  fi
  if [[ ${#cuda_library_dirs[@]} -gt 0 ]]; then
    printf -v joined '%s:' "${cuda_library_dirs[@]}"
    export LD_LIBRARY_PATH="${joined%:}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
  fi
  if ! "${PYTHON_EXECUTABLE}" -c \
    'import cupy as cp; assert cp.cuda.runtime.getDeviceCount() > 0' >/dev/null; then
    echo "CuPy cannot access a CUDA GPU; PCT map generation cannot continue." >&2
    return 1
  fi
}

configure_python_cuda_runtime
build_args=(
  --pcd "${SOURCE_PCD}"
  --output "${BUILD_TOMOGRAM}"
  --xy-dilation-cells "${XY_DILATION_CELLS}"
)
if [[ "${PROFILE}" == nx-large ]]; then
  build_args+=(
    --profile-name nx-large
    --resolution "${RESOLUTION:-0.2}"
    --kernel-size 5
    --slope-max 1.2386243738717622
  )
elif [[ -n "${RESOLUTION}" ]]; then
  build_args+=(--resolution "${RESOLUTION}")
fi
if [[ -n "${GROUND_H}" ]]; then
  build_args+=(--ground-h "${GROUND_H}")
fi
"${PYTHON_EXECUTABLE}" "${BUILDER}" "${build_args[@]}"

source_sha="$(sha256sum "${SOURCE_PCD}" | awk '{print $1}')"
localization_sha="$(sha256sum "${LOCALIZATION_PCD}" | awk '{print $1}')"
"${PYTHON_EXECUTABLE}" - \
  "${BUILD_TOMOGRAM}" "${source_sha}" "${localization_sha}" \
  "$(basename "${LOCALIZATION_PCD}")" "${PAIR_MANIFEST}" <<'PY'
import json
import os
import pickle
import sys

with open(sys.argv[1], 'rb') as stream:
    payload = pickle.load(stream)
data = payload.get('data')
if getattr(data, 'ndim', None) != 4 or data.shape[0] < 5 or data.shape[1] < 1:
    raise RuntimeError('invalid PCT tomogram')
if payload.get('source_pcd_sha256') != sys.argv[2]:
    raise RuntimeError('PCD checksum does not match tomogram metadata')
payload['navigation_map_schema_version'] = 2
payload['localization_pcd_sha256'] = sys.argv[3]
payload['localization_pcd_name'] = sys.argv[4]
if sys.argv[5]:
  with open(sys.argv[5], 'r', encoding='utf-8') as stream:
    manifest = json.load(stream)
  payload['mapping_session_name'] = manifest.get('map_name')
  payload['mapping_coordinate_frame'] = manifest.get('coordinate_frame')
  payload['localization_max_range_m'] = float(
    manifest['localization_pcd']['max_range_m']
  )
  payload['pct_source_max_range_m'] = float(
    manifest['pct_source_pcd']['max_range_m']
  )
  if manifest.get('registration_max_range_m') is not None:
    payload['registration_max_range_m'] = float(
      manifest['registration_max_range_m']
    )
temporary = sys.argv[1] + '.metadata.%d' % os.getpid()
try:
  with open(temporary, 'wb') as stream:
    pickle.dump(payload, stream, protocol=pickle.HIGHEST_PROTOCOL)
    stream.flush()
    os.fsync(stream.fileno())
  os.replace(temporary, sys.argv[1])
finally:
  if os.path.exists(temporary):
    os.unlink(temporary)
PY

copy_atomic() {
  local source="$1"
  local destination="$2"
  local temporary="${destination}.new.$$"
  rm -f "${temporary}"
  cp --reflink=auto -p "${source}" "${temporary}"
  chmod 664 "${temporary}"
  mv -Tf "${temporary}" "${destination}"
}

copy_atomic "${LOCALIZATION_PCD}" "${NAMED_PCD}"
if [[ "${DUAL_MAP}" == true ]]; then
  copy_atomic "${SOURCE_PCD}" "${NAMED_PCT_SOURCE}"
  copy_atomic "${PAIR_MANIFEST}" "${NAMED_PAIR_MANIFEST}"
else
  rm -f "${NAMED_PCT_SOURCE}" "${NAMED_PAIR_MANIFEST}"
fi
copy_atomic "${BUILD_TOMOGRAM}" "${NAMED_TOMOGRAM}"
if [[ "${ACTIVATE}" == true ]]; then
  "${PYTHON_EXECUTABLE}" "${NAVIGATION_MAP_SELECTOR}" \
    --root "${ROOT_DIR}" \
    --name "fast_lio_${NAME}"
fi

printf 'LOCALIZATION_PCD=%s\nPCT_SOURCE_PCD=%s\nTOMOGRAM=%s\n' \
  "${NAMED_PCD}" \
  "$([[ "${DUAL_MAP}" == true ]] && printf '%s' "${NAMED_PCT_SOURCE}" || printf '%s' "${NAMED_PCD}")" \
  "${NAMED_TOMOGRAM}"
if [[ "${ACTIVATE}" == true ]]; then
  printf 'ACTIVE_LOCALIZATION_MAP=%s\nACTIVE_PCT_SOURCE=%s\nACTIVE_PCT_TOMOGRAM=%s\n' \
    "${ACTIVE_PCD}" \
    "$([[ "${DUAL_MAP}" == true ]] && printf '%s' "${ACTIVE_PCT_SOURCE}" || printf '%s' "${ACTIVE_PCD}")" \
    "${ACTIVE_TOMOGRAM}"
fi
